FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine as sdk
WORKDIR /src
COPY GrpcChat.Client ./GrpcChat.Client/
COPY GrpcChat.Contracts ./GrpcChat.Contracts/
RUN dotnet publish --configuration=Release GrpcChat.Client/GrpcChat.Client.csproj -o /app

FROM mcr.microsoft.com/dotnet/aspnet:3.1-alpine as runtime
WORKDIR /app
COPY --from=sdk /app .

ENTRYPOINT [ "dotnet", "GrpcChat.Client.dll" ]
